# -*- coding: utf-8 -*-
"""SummerT_toolsTest_Validate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J1jUmn4jVwy0YBG8BRNCIwuo4gLKwdKY
"""

import os
import pandas as pd

CONTRACTS_FILE = "selected_contracts.csv"
FINDINGS_FILE = "findings_validation.csv"

def load_ground_truth(path: str) -> pd.DataFrame:
    df = pd.read_csv(path)
    df["name"] = df["contract"].apply(
        lambda p: os.path.splitext(os.path.basename(p.replace("\\", "/")))[0].lower()
    )
    return df[["name", "category"]].rename(columns={"category": "ground_truth_category"})


def load_findings(path: str) -> pd.DataFrame:
    df = pd.read_csv(path)
    df["contract"] = df["contract"].str.lower()
    return df


def build_binary_detection_matrix(findings: pd.DataFrame, all_contracts, all_categories, all_tools):
    detected_pairs = (
        findings[["tool", "contract", "detected_category"]]
        .drop_duplicates()
    )

    matrices = {}
    for tool in all_tools:
        sub = detected_pairs[detected_pairs["tool"] == tool]
        mat = pd.DataFrame(0, index=all_contracts, columns=all_categories)
        for _, row in sub.iterrows():
            if row["contract"] in mat.index and row["detected_category"] in mat.columns:
                mat.loc[row["contract"], row["detected_category"]] = 1
        matrices[tool] = mat
    return matrices


def precision_recall_f1(tp: int, fp: int, fn: int):
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    f1 = (2 * precision * recall / (precision + recall)) if (precision + recall) > 0 else 0.0
    return precision, recall, f1


def compute_per_tool_category_metrics(matrices, ground_truth: pd.Series, all_categories, total_contracts: int):
    rows = []
    for tool, mat in matrices.items():
        for category in all_categories:
            is_positive = (ground_truth == category)
            detected = mat[category] == 1

            tp = int((is_positive & detected).sum())
            fn = int((is_positive & ~detected).sum())
            fp = int((~is_positive & detected).sum())
            tn = total_contracts - tp - fn - fp

            precision, recall, f1 = precision_recall_f1(tp, fp, fn)

            rows.append({
                "tool": tool,
                "category": category,
                "TP": tp,
                "FP": fp,
                "FN": fn,
                "TN": tn,
                "precision": round(precision, 3),
                "recall": round(recall, 3),
                "f1": round(f1, 3),
            })
    return pd.DataFrame(rows)


def compute_tool_summary(per_category_df: pd.DataFrame) -> pd.DataFrame:
    summary_rows = []
    for tool, g in per_category_df.groupby("tool"):
        macro_p, macro_r, macro_f1 = g["precision"].mean(), g["recall"].mean(), g["f1"].mean()

        tp_sum, fp_sum, fn_sum, tn_sum = g["TP"].sum(), g["FP"].sum(), g["FN"].sum(), g["TN"].sum()
        micro_p, micro_r, micro_f1 = precision_recall_f1(tp_sum, fp_sum, fn_sum)

        summary_rows.append({
            "tool": tool,
            "category": "ALL_CATEGORIES",
            "TP": tp_sum,
            "FP": fp_sum,
            "FN": fn_sum,
            "TN": tn_sum,
            "precision": round(micro_p, 3),
            "recall": round(micro_r, 3),
            "f1": round(micro_f1, 3),
        })
    return pd.DataFrame(summary_rows).sort_values("f1", ascending=False)


def main():
    gt_df = load_ground_truth(CONTRACTS_FILE)
    findings = load_findings(FINDINGS_FILE)

    all_contracts = sorted(gt_df["name"].unique())
    all_categories = sorted(gt_df["ground_truth_category"].unique())
    all_tools = sorted(findings["tool"].unique())
    total_contracts = len(all_contracts)

    ground_truth = gt_df.set_index("name")["ground_truth_category"]
    ground_truth = ground_truth.reindex(all_contracts)

    matrices = build_binary_detection_matrix(findings, all_contracts, all_categories, all_tools)

    per_category_df = compute_per_tool_category_metrics(matrices, ground_truth, all_categories, total_contracts)
    summary_df = compute_tool_summary(per_category_df)

    per_category_df = per_category_df.sort_values(["tool", "category"]).reset_index(drop=True)

    final_df = pd.concat([per_category_df, summary_df], ignore_index=True)
    final_df.to_csv("precision_recall_f1_results.csv", index=False, encoding="utf-8-sig")

    print(final_df.to_string(index=False))

    return final_df


if __name__ == "__main__":
    main()